### ISSUE TITLE
Rename typeUuid to typeUuidBinary to allow use of normal UUIDs

### ISSUE THREAD

**Issue by faustbrian** [spatie/laravel-binary-uuid#14]
Currently it is not possible to use normal UUIDs for other fields as the `typeUuid` method overwrites the original uuid method that Laravel comes with.

It would be good if it would be possible to have 2 distinct functions for `uuid` and `uuidBinary` to allow use of both as the package doesn't automatically store every uuid type field as an optimised UUID.

A use case for that would be invite codes where you maybe choose to use UUIDs as tokens but if you use this package you will have to either use `string` or `char(36)`.

**Comment by freekmurze** [comment]
I like the idea, but I don't see how we can implement this now in a non breaking way. Closing for now, but will take a look again when creating a new major version

**Comment by faustbrian** [comment]
What would you recommend as a workaround then? Currently you can either use this package for primary keys and use unoptimised field types for other UUID fields or just don't use this package at all.

**Comment by freekmurze** [comment]
L

**Comment by freekmurze** [comment]
Let's do this is in a non breaking way. Let's leave `typeUuid ` as it is for new and add `typeUuidText`.

In the next major version we could remove the override of `typeUuid ` and add `typeUuidBinary`.

I'd accept a PR for this.

**Comment by faustbrian** [comment]
https://github.com/spatie/laravel-binary-uuid/pull/15
https://github.com/spatie/laravel-binary-uuid/pull/16

**Comment by brendt** [comment]
There's a little bit more to it than this I'm afraid.

Adding a custom type was also the first solution I went for, but it only solves half the problem.

#15 and #16 add the type to the Grammar classes, but there's no support yet to call that method from the blueprint.

```php
Schema::create('table_name', function (Blueprint $table) {
    $table->uuid('uuid');
    $table->primary('uuid');

    $table->uuidText('other_uuid'); // won't work
});
```

You could extend Laravel's `Blueprint` class to add the functionality, but that class internally is always re-created on the fly by `Schema`. So you'll still never get your `Blueprint` implementation because `Schema` internally uses the Laravel implementation.

One possible workaround could be to override the `Schema` dependency at whole, but that's can have a very big impact on the codebase. I feel this package shouldn't carry that responsibility.

This problem is the exact reason we're overriding the `uuid` type on the Grammar level. I'd much more prefer to see something like this:

```php
Schema::create('table_name', function (Blueprint $table) {
    $table->uuidBinary('uuid');
});
```

But it's not possible.

Also note that using the `->binary` method on a blueprint actually doesn't create a `BINARY` field, but rather a `BLOB` field, which can't be indexed because there's no way to configure its length (which is required for MySQL indices).

The way to add normal UUID fields with the `->char` method.

```php
Schema::create('table_name', function (Blueprint $table) {
    $table->char('textual_uuid', 36);
});
```

The only way to really solve this issue is if there was a possibility to configure which `Blueprint` class is used, which requires a change in Laravel itself.

For reference, I'm talking about this line in Laravel: https://github.com/laravel/framework/blob/5.5/src/Illuminate/Database/Schema/Builder.php#L268

Oh and about that resolver: you cannot set it from a service provider, because a `Builder` is always made with `new`: https://github.com/laravel/framework/blob/5.5/src/Illuminate/Database/Eloquent/Model.php#L904

**Comment by faustbrian** [comment]
This could be a possible solution @brendt 

```php
<?php

class MysqlServiceProvider extends ServiceProvider
{
    public function register()
    {
        $this->app->bind('db.connection.mysql', SpatieMySqlConnection::class);
    }
}
```

```php
<?php

use Illuminate\Database\MySqlConnection as BaseMySqlConnection;
use Illuminate\Database\Schema\MySqlBuilder;

class MySqlConnection extends BaseMySqlConnection
{
    public function getSchemaBuilder()
    {
        if (is_null($this->schemaGrammar)) {
            $this->useDefaultSchemaGrammar();
        }

        $builder = new MySqlBuilder($this);

        $builder->blueprintResolver(function ($table, $callback) {
            return new SpatieBlueprint($table, $callback);
        });

        return $builder;
    }
}
```

```php
<?php

use Illuminate\Database\Schema\Blueprint as BaseBlueprint;
use Illuminate\Support\Facades\DB;

class Blueprint extends BaseBlueprint
{
    public function uuid()
    {
        return $this->addColumn('uuid', $column);
    }
    
    public function uuidBinary()
    {
        return $this->addColumn('uuidBinary', $column);
    }
}
```

**Comment by brendt** [comment]
Yes. Though I'd like to avoid overriding a class like `MySqlConnection`. It doesn't feel right if this package starts messing with such a key component.

**Comment by steve3d** [comment]
agreed with @brendt , you should use `$table->char('textual_uuid', 36)` to add a normal text uuid.

**Comment by brendt** [comment]
FYI the possibilities to add better support in the core can be found here: https://github.com/laravel/internals/issues/645

There's no consensus though, yet.

**Comment by brendt** [comment]
Turns out `Blueprint` is macroable. So we're able to add a dedicated method for creating a binary UUID column. I've pushed a branch called v2, containing this change: https://github.com/spatie/laravel-binary-uuid/commit/a3fada6c22cbf771c9ed1285b68b8f46ccfbe9f6

We'll be able to use this solution if there's no built in binary support once Laravel 5.6 arrives.

**Comment by francislavoie** [comment]
Mildly related question, if I wanted to extend the grammar myself to add something else, how would I do it such that it's still compatible with binary UUID? I want to add `MEDIUMBLOB` support to the grammar since I only use MySQL

**Comment by brendt** [comment]
Because Grammar classes are not macroable; the only possibility is to extend `Spatie\BinaryUuid\MySqlGrammar` and manually register it on the connection.

```php
$connection = app('db')->connection();
$connection->setSchemaGrammar($this->createGrammarFromConnection($connection));
```

See https://github.com/spatie/laravel-binary-uuid/blob/master/src/UuidServiceProvider.php#L27-L45 for the full implementation we're using.
