### ISSUE TITLE
Configuration option for using UUID v4 instead of v1

### ISSUE THREAD

**Issue by francislavoie** [spatie/laravel-binary-uuid#41]
I'm thinking that abstracting https://github.com/spatie/laravel-binary-uuid/blob/master/src/HasBinaryUuid.php#L18 into the service provider would be nice. Maybe configurable per model instead of the service provider?

I guess it would mean losing out on some indexing performance, but for UUIDs that are used externally to the application, it would provide anonymity.

Thanks

**Comment by Cayan** [comment]
This seems like a great update for this project

**Comment by brendt** [comment]
This package was built with binary bit-shifting in mind. That means it'll only makes sense to use UUID v1. Storing UUIDs as binary was a side effect of it. 

When we build v2, we'll split binary columns and generation of UUIDs better, so that you'll have full control over it on model level. Furthermore, there's talk that a binary UUID column will be added natively in Laravel, but there's no ETA for that one. 

Same goes for this package: we are not actively working on a new version at the moment. So we'll keep this issue in mind, but I'm going to close it for now.
