### ISSUE TITLE
[Question] Infinite recursion for getAttribute when present in multiple traits

### ISSUE THREAD

**Issue by vpratfr** [spatie/laravel-binary-uuid#56]
I am using this library along with some other libraries which also provide traits for the getAttribute method.

I cannot manage to find the right way to use both traits for the same model class.

Here is the corresponding StackOverflow question: https://stackoverflow.com/questions/51823409/detect-recursion-when-overridding-trait-methods which has some more details about the use case.

Any input? Ideas? You may have already solve that as your libraries often override that method.

**Comment by brendt** [comment]
Did the `private` solution work for you (https://stackoverflow.com/a/51823612) ?

My first thought, before having read the SO answer was also to import the trait methods with a different name and compose them yourself, as you did.

If all else fails, I'm afraid you'll have to make a separate trait, combining the two. It'll mean you'll implement a piece of library logic in your own project code though 😥

I'm going to close this issue, but feel free to still comment, I'd love to hear your solution.

PS: I considered extracting our `getAttribute` logic into a separate helper function. Our trait will still implement `getAttribute`, but it'll call that helper function instead. This means that if you want to combine functionality of two libraries, you can call the helper function instead of having to privately import the methods and loop over them. I don't think that's an actual improvement though..

**Comment by vpratfr** [comment]
For anyone facing the same issue.

Making the trait alias the functions as `private` worked. I guess that is the proper way to solve the issue.

I also do not think moving logic to a separate function would help much. I would not like to override that getAttribute function by calling explicitly another function of each trait (which in turn may have a different name in each library because of the lack of convention).

Nothing to change here thus :)

**Comment by brendt** [comment]
Thanks for sharing the solution!
