### ISSUE TITLE
[BUG]Stop overriding `getKeyName` method of Model class.

### ISSUE THREAD

**Issue by yaquawa** [spatie/laravel-binary-uuid#59]
Hi!
Thanks for the great works!!

I found a problem to redefine primary key of models.

In the `spatie/laravel-binary-uuid/src/HasBinaryUuid.php`

where this `getKeyName` method is overriding `Illuminate\Database\Eloquent\Model::getKeyName`. Which cause problems.

```php
trait HasBinaryUuid{
    public function getKeyName()
    {
        return 'uuid';
    }
}
```

according to your documentation:
> If don't like the primary key named uuid you can manually specify $primaryKey. Don't forget set $incrementing to false.
> 
> use Illuminate\Database\Eloquent\Model;
> use Spatie\BinaryUuid\HasBinaryUuid;
```php
use Illuminate\Database\Eloquent\Model;
use Spatie\BinaryUuid\HasBinaryUuid;

class TestModel extends Model
{
    use HasBinaryUuid;

    public $incrementing = false;
    
    public $primaryKey = 'uuid';  // THIS WON'T WORK! Because primaryKey is hardcoded in the `getKeyName` method.
}
```
To fix it just remove the `getKeyName` method from the `HasBinaryUuid` trait.

Am I missing something…!? Because obviously overriding parent's method and hardcoding options is a bad idea in the first place…  or maybe providing a config file would be nicer just like the https://github.com/EmadAdly/laravel-uuid/blob/master/src/LaravelUuidServiceProvider.php#L25 dose so.

**Comment by brendt** [comment]
Indeed, it's a bug. At one point we've simplified the package by deprecating the separate `HasUuidPrimaryKey`, and moving the behaviour to the `HasBinaryUuid` trait. This included the `getKeyName` method. (https://github.com/spatie/laravel-binary-uuid/commit/ed1a38e56d5dd41919cbd31b7f913fe74ad2c4d0)

Unfortunately, we cannot simply remove the `getKeyName` method, as it will break the default behaviour of the package. We also cannot do a check on `property_exists($this, 'primaryKey')` because `$primaryKey` is by default `id` on Eloquent models.

I'm afraid that the only way of fixing this in a non-breaking way, is to update the README, stating that you'll have to override `getKeyName` in your model, like so:

```
public function getKeyName()
{
    return 'custom_uuid';
}
```

We've been talking about v2 for a while now, and this is definitely one of the things that can be properly fixed there. I've updated the README for now, and we'll come back to this once we're working on the next major version.
