### ISSUE TITLE
Relation model saving causes "UTF-8" Error

### ISSUE THREAD

**Issue by steintoon** [spatie/laravel-binary-uuid#88]
I'm struggling with relationship models which contains uuid. Trying to save model which has uuid as FK. 
Saving model gives "Malformed UTF-8 characters, possibly incorrectly encoded" as a response.

Model looks like:

```php
class Follow extends Model
{
    use HasBinaryUuid;

    protected $uuids = [
        'corporation_uuid'
    ];
    

    public function user(){
        return $this->belongsTo(User::class);
    }

    public function corporation(){
        return $this->belongsTo(Corporation::class);
    }
```
Controller function looks like:

```php
public function store($corporation)
    {
        $user = auth('api')->user();
        if($user->isFollowing($corporation)){
            return response([
                'message' => 'Already following'], Response::HTTP_OK);
        }

        $corporation = Corporation::withUuid($corporation)->first();

        $follow = new Follow();
        $follow->user_id = $user->id;

        $corporation->follows()->save($follow);
        
        return response([
            'message' => 'Followed'], Response::HTTP_OK);
    }
```

Is there any workaround saving with uuid as FK?
Thanks.

**Comment by Willidan** [comment]
Had the same issue. For me this workaround is good:

Any time you insert FK uuid attribute:
`$model->fk_uuid = MyModel::encodeUuid($uuid);`

Then in your MyModel.php add your 'fk_uuid' to $hidden array so it won't be automatically converted:
```
protected $hidden = [
    'fk_uuid'
];
```
In model file also - to get uuid back in human readable format:

```
    public function getForeignUuidAttribute()
    {
        return self::decodeUuid($this->attributes['fk_uuid']);
    }

    protected $appends = ['foreign_uuid'];
```
Now any time you convert your model to array or try send it by json it will contain 'foreign_uuid' instead of 'fk_uuid', and with proper form. Binary format of the uuid type column in you DB stays the same.

**Comment by freekmurze** [comment]
This package has been abandoned. Alternatives: https://github.com/michaeldyrynda/laravel-efficient-uuid & https://github.com/michaeldyrynda/laravel-model-uuid
