### ISSUE TITLE
Disable blueprint override

### ISSUE THREAD

**Issue by blakethepatton** [spatie/laravel-binary-uuid#90]
Is there a way to disable the blueprint override for uuid fields? Maybe a config var that enables/disables that behavior? I'd rather just create the `bin(16)` columns for now instead of updating all the rest of the UUIDs in the rest of my project as well as any packages we're pulling in that use uuids. 

```php
public function boot()
    {
        if ( !env('DISABLE_UUID_BLUEPRINT_OVERRIDE', false) ) { 
              /** @var \Illuminate\Database\Connection $connection */
             $connection = app('db')->connection();
             $connection->setSchemaGrammar($this->createGrammarFromConnection($connection));
         }
         $this->optimizeUuids();
    }
```

**Comment by brendt** [comment]
Because of the many incompatibilities with recent Laravel projects, we've decided it's not feasible anymore to support the package in its current form. You can read more about it here: https://github.com/spatie/laravel-binary-uuid/issues

Your problem could be solved with a proper v2, but we have no plans on making that. You're free to fork the repository and make your own version of this package.
